Repository Nityaa1802/Shadow_Project, pull requests merged in 2023-06, with the labels that each got.

#16 make change to user and project entity
  src/main/java/com/example/shadow_project/entity/Answer/Answers.java
  src/main/java/com/example/shadow_project/entity/Doubt/Doubt.java
  src/main/java/com/example/shadow_project/entity/Project/Project.java
  src/main/java/com/example/shadow_project/entity/Project/ProjectController.java
  src/main/java/com/example/shadow_project/entity/Project/ProjectDto.java
  src/main/java/com/example/shadow_project/entity/Project/ProjectRepo.java
  src/main/java/com/example/shadow_project/entity/Project/ProjectService.java
  src/main/java/com/example/shadow_project/entity/Project/ProjectServiceImpl.java
  src/main/java/com/example/shadow_project/entity/TeamMember/TeamMember.java
  src/main/java/com/example/shadow_project/entity/User/UserController.java
  src/main/java/com/example/shadow_project/entity/User/UserDto.java
  src/main/java/com/example/shadow_project/entity/User/UserRepo.java
  src/main/java/com/example/shadow_project/entity/User/UserResponse.java
  src/main/java/com/example/shadow_project/entity/User/UserService.java
  src/main/java/com/example/shadow_project/entity/User/UserServiceImpl.java
Labels: p1, feature, hold

#20 #14 Created Upload Api to uplaod Announcement
  src/main/java/com/example/shadow_project/entity/Announcment/AnnouncementController.java
  src/main/java/com/example/shadow_project/entity/Announcment/AnnouncementDto.java
  src/main/java/com/example/shadow_project/entity/Announcment/AnnouncementRepo.java
  src/main/java/com/example/shadow_project/entity/Announcment/AnnouncementService.java
  src/main/java/com/example/shadow_project/entity/Announcment/AnnouncementServiceImpl.java
  src/main/java/com/example/shadow_project/entity/Answer/AnswersDto.java
  src/main/java/com/example/shadow_project/entity/Project/ProjectController.java
Labels: p1, feature, hold

#22 #21 Created upload apis to upload Doubt
  src/main/java/com/example/shadow_project/entity/Answer/AnswerDto.java
  src/main/java/com/example/shadow_project/entity/Answer/Answers.java
  src/main/java/com/example/shadow_project/entity/Doubt/DoubtController.java
  src/main/java/com/example/shadow_project/entity/Doubt/DoubtDto.java
  src/main/java/com/example/shadow_project/entity/Doubt/DoubtRepo.java
  src/main/java/com/example/shadow_project/entity/Doubt/DoubtService.java
  src/main/java/com/example/shadow_project/entity/Doubt/DoubtServiceImpl.java
Labels: p1, feature, hold

#31 #28 created api to fetch top 6 announcements
  src/main/java/com/example/shadow_project/entity/Announcment/AnnouncementController.java
  src/main/java/com/example/shadow_project/entity/Announcment/AnnouncementService.java
  src/main/java/com/example/shadow_project/entity/Announcment/AnnouncementServiceImpl.java
Labels: enhancement, feature

#30 #27 top 6 doubts api created
  src/main/java/com/example/shadow_project/entity/Doubt/DoubtController.java
  src/main/java/com/example/shadow_project/entity/Doubt/DoubtRepo.java
  src/main/java/com/example/shadow_project/entity/Doubt/DoubtService.java
  src/main/java/com/example/shadow_project/entity/Doubt/DoubtServiceImpl.java
  src/main/java/com/example/shadow_project/entity/Project/ProjectRepo.java
Labels: feature

#32 #26 created api to fetch latest 30 days announcement
  src/main/java/com/example/shadow_project/entity/Announcment/AnnouncementController.java
  src/main/java/com/example/shadow_project/entity/Announcment/AnnouncementService.java
  src/main/java/com/example/shadow_project/entity/Announcment/AnnouncementServiceImpl.java
Labels: feature

#33 #25 created update password api
  src/main/java/com/example/shadow_project/entity/User/UserController.java
  src/main/java/com/example/shadow_project/entity/User/UserRepo.java
  src/main/java/com/example/shadow_project/entity/User/UserService.java
  src/main/java/com/example/shadow_project/entity/User/UserServiceImpl.java
Labels: enhancement

#36 #29 created apis to fetch all doubts and announcement also included pagination
  src/main/java/com/example/shadow_project/entity/Announcment/AnnouncementController.java
  src/main/java/com/example/shadow_project/entity/Announcment/AnnouncementRepo.java
  src/main/java/com/example/shadow_project/entity/Announcment/AnnouncementService.java
  src/main/java/com/example/shadow_project/entity/Announcment/AnnouncementServiceImpl.java
  src/main/java/com/example/shadow_project/entity/Doubt/DoubtController.java
  src/main/java/com/example/shadow_project/entity/Doubt/DoubtRepo.java
  src/main/java/com/example/shadow_project/entity/Doubt/DoubtService.java
  src/main/java/com/example/shadow_project/entity/Doubt/DoubtServiceImpl.java
  src/main/java/com/example/shadow_project/entity/Project/ProjectRepo.java
Labels: feature

#37 #26 updated the code of last 30 days announcement
  src/main/java/com/example/shadow_project/entity/Announcment/AnnouncementServiceImpl.java
Labels: feature

#38 #26 done changes
  src/main/java/com/example/shadow_project/entity/Announcment/AnnouncementServiceImpl.java
Labels: feature

#39 #35 started with working on domain section
  src/main/java/com/example/shadow_project/entity/Domain/Domain.java
  src/main/java/com/example/shadow_project/entity/Domain/DomainController.java
  src/main/java/com/example/shadow_project/entity/Domain/DomainRepo.java
  src/main/java/com/example/shadow_project/entity/Domain/DomainService.java
  src/main/java/com/example/shadow_project/entity/Domain/DomainServiceImpl.java
Labels: feature, hold

#41 done some changes
  src/main/java/com/example/shadow_project/entity/Domain/DomainController.java
  src/main/java/com/example/shadow_project/entity/Domain/DomainRepo.java
  src/main/java/com/example/shadow_project/entity/Domain/DomainService.java
  src/main/java/com/example/shadow_project/entity/Domain/DomainServiceImpl.java
Labels: feature
